<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="hal-51" name="com.bleulace.domain.AuthenticationTest" tests="1" failures="1" timestamp="9 Aug 2013 20:52:37 GMT" time="0.000" errors="0">
  <testcase name="foo" time="0.000" classname="com.bleulace.domain.AuthenticationTest">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at com.bleulace.cqrs.command.CommandGatewayAwareAspect.ajc$interMethod$com_bleulace_cqrs_command_CommandGatewayAwareAspect$com_bleulace_cqrs_command_CommandGatewayAware$sendAndWait(CommandGatewayAwareAspect.aj:37)
	at com.bleulace.domain.AuthenticationTest.sendAndWait(AuthenticationTest.java:1)
	at com.bleulace.cqrs.command.CommandGatewayAwareAspect.ajc$interMethodDispatch1$com_bleulace_cqrs_command_CommandGatewayAwareAspect$com_bleulace_cqrs_command_CommandGatewayAware$sendAndWait(CommandGatewayAwareAspect.aj)
	at com.bleulace.domain.AuthenticationTest.beforeClass(AuthenticationTest.java:47)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:564)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:213)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:653)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:335)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:330)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </failure>
  </testcase> <!-- foo -->
</testsuite> <!-- com.bleulace.domain.AuthenticationTest -->
